version: '3.4'

services:

  api.graceful-shutdown.dev:
    container_name: api.graceful-shutdown.dev
    image: nginx:1.19.2
    working_dir: /application
    volumes:
      - ./nginx-local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9048:80"
    networks:
      - bubble
    depends_on:
      - app.graceful-shutdown.dev

  app.graceful-shutdown.dev:
    container_name: app.graceful-shutdown.dev
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    networks:
      - bubble

networks:
  bubble:
    external: true
